#PLAN1
INSERT INTO OBROK
VALUES(1, 'Doručak1', 'Doručak', 'PON;SRE;PET;NED', 'ut sem viverra aliquet eget sit amet tellus cras adipiscing', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. In eu mi bibendum neque. Facilisi morbi tempus iaculis urna id volutpat lacus laoreet non. Turpis massa tincidunt dui ut. A diam sollicitudin tempor id. Volutpat commodo sed egestas egestas fringilla phasellus faucibus. Felis eget nunc lobortis mattis aliquam. Rhoncus dolor purus non enim praesent elementum. Egestas dui id ornare arcu odio ut sem nulla. Sed viverra ipsum nunc aliquet bibendum enim facilisis gravida.');

INSERT INTO OBROK
VALUES(2, 'Doručak2', 'Doručak', 'UTO;ČET;SUB', 'ut sem viverra aliquet eget sit amet tellus cras adipiscing', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. In eu mi bibendum neque. Facilisi morbi tempus iaculis urna id volutpat lacus laoreet non. Turpis massa tincidunt dui ut. A diam sollicitudin tempor id. Volutpat commodo sed egestas egestas fringilla phasellus faucibus. Felis eget nunc lobortis mattis aliquam. Rhoncus dolor purus non enim praesent elementum. Egestas dui id ornare arcu odio ut sem nulla. Sed viverra ipsum nunc aliquet bibendum enim facilisis gravida.');

INSERT INTO OBROK
VALUES(3, 'Prepodnevna užina1', 'Prepodnevna užina', 'PON;SRE;PET;NED', 'ut sem viverra aliquet eget sit amet tellus cras adipiscing', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. In eu mi bibendum neque. Facilisi morbi tempus iaculis urna id volutpat lacus laoreet non. Turpis massa tincidunt dui ut. A diam sollicitudin tempor id. Volutpat commodo sed egestas egestas fringilla phasellus faucibus. Felis eget nunc lobortis mattis aliquam. Rhoncus dolor purus non enim praesent elementum. Egestas dui id ornare arcu odio ut sem nulla. Sed viverra ipsum nunc aliquet bibendum enim facilisis gravida.');

INSERT INTO OBROK
VALUES(4, 'Prepodnevna užina2', 'Prepodnevna užina', 'UTO;ČET;SUB', 'ut sem viverra aliquet eget sit amet tellus cras adipiscing', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. In eu mi bibendum neque. Facilisi morbi tempus iaculis urna id volutpat lacus laoreet non. Turpis massa tincidunt dui ut. A diam sollicitudin tempor id. Volutpat commodo sed egestas egestas fringilla phasellus faucibus. Felis eget nunc lobortis mattis aliquam. Rhoncus dolor purus non enim praesent elementum. Egestas dui id ornare arcu odio ut sem nulla. Sed viverra ipsum nunc aliquet bibendum enim facilisis gravida.');

INSERT INTO OBROK
VALUES(5, 'Ručak1', 'Ručak', 'PON;SRE;PET;NED', 'ut sem viverra aliquet eget sit amet tellus cras adipiscing', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. In eu mi bibendum neque. Facilisi morbi tempus iaculis urna id volutpat lacus laoreet non. Turpis massa tincidunt dui ut. A diam sollicitudin tempor id. Volutpat commodo sed egestas egestas fringilla phasellus faucibus. Felis eget nunc lobortis mattis aliquam. Rhoncus dolor purus non enim praesent elementum. Egestas dui id ornare arcu odio ut sem nulla. Sed viverra ipsum nunc aliquet bibendum enim facilisis gravida.');

INSERT INTO OBROK
VALUES(6, 'Ručak2', 'Ručak', 'UTO;ČET;SUB', 'ut sem viverra aliquet eget sit amet tellus cras adipiscing', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. In eu mi bibendum neque. Facilisi morbi tempus iaculis urna id volutpat lacus laoreet non. Turpis massa tincidunt dui ut. A diam sollicitudin tempor id. Volutpat commodo sed egestas egestas fringilla phasellus faucibus. Felis eget nunc lobortis mattis aliquam. Rhoncus dolor purus non enim praesent elementum. Egestas dui id ornare arcu odio ut sem nulla. Sed viverra ipsum nunc aliquet bibendum enim facilisis gravida.');

INSERT INTO OBROK
VALUES(7, 'Popodnevna užina1', 'Popodnevna užina', 'PON;SRE;PET;NED', 'ut sem viverra aliquet eget sit amet tellus cras adipiscing', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. In eu mi bibendum neque. Facilisi morbi tempus iaculis urna id volutpat lacus laoreet non. Turpis massa tincidunt dui ut. A diam sollicitudin tempor id. Volutpat commodo sed egestas egestas fringilla phasellus faucibus. Felis eget nunc lobortis mattis aliquam. Rhoncus dolor purus non enim praesent elementum. Egestas dui id ornare arcu odio ut sem nulla. Sed viverra ipsum nunc aliquet bibendum enim facilisis gravida.');

INSERT INTO OBROK
VALUES(8, 'Popodnevna užina2', 'Popodnevna užina', 'UTO;ČET;SUB', 'ut sem viverra aliquet eget sit amet tellus cras adipiscing', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. In eu mi bibendum neque. Facilisi morbi tempus iaculis urna id volutpat lacus laoreet non. Turpis massa tincidunt dui ut. A diam sollicitudin tempor id. Volutpat commodo sed egestas egestas fringilla phasellus faucibus. Felis eget nunc lobortis mattis aliquam. Rhoncus dolor purus non enim praesent elementum. Egestas dui id ornare arcu odio ut sem nulla. Sed viverra ipsum nunc aliquet bibendum enim facilisis gravida.');

INSERT INTO OBROK
VALUES(9, 'Večera1', 'Večera', 'PON;SRE;PET;NED', 'ut sem viverra aliquet eget sit amet tellus cras adipiscing', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. In eu mi bibendum neque. Facilisi morbi tempus iaculis urna id volutpat lacus laoreet non. Turpis massa tincidunt dui ut. A diam sollicitudin tempor id. Volutpat commodo sed egestas egestas fringilla phasellus faucibus. Felis eget nunc lobortis mattis aliquam. Rhoncus dolor purus non enim praesent elementum. Egestas dui id ornare arcu odio ut sem nulla. Sed viverra ipsum nunc aliquet bibendum enim facilisis gravida.');

INSERT INTO OBROK
VALUES(10, 'Večera2', 'Večera', 'UTO;ČET;SUB', 'ut sem viverra aliquet eget sit amet tellus cras adipiscing', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. In eu mi bibendum neque. Facilisi morbi tempus iaculis urna id volutpat lacus laoreet non. Turpis massa tincidunt dui ut. A diam sollicitudin tempor id. Volutpat commodo sed egestas egestas fringilla phasellus faucibus. Felis eget nunc lobortis mattis aliquam. Rhoncus dolor purus non enim praesent elementum. Egestas dui id ornare arcu odio ut sem nulla. Sed viverra ipsum nunc aliquet bibendum enim facilisis gravida.');

#PLAN2
INSERT INTO OBROK
VALUES(11, 'Doručak1', 'Doručak', 'UTO;ČET;SUB', 'ut sem viverra aliquet eget sit amet tellus cras adipiscing', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. In eu mi bibendum neque. Facilisi morbi tempus iaculis urna id volutpat lacus laoreet non. Turpis massa tincidunt dui ut. A diam sollicitudin tempor id. Volutpat commodo sed egestas egestas fringilla phasellus faucibus. Felis eget nunc lobortis mattis aliquam. Rhoncus dolor purus non enim praesent elementum. Egestas dui id ornare arcu odio ut sem nulla. Sed viverra ipsum nunc aliquet bibendum enim facilisis gravida.');

INSERT INTO OBROK
VALUES(12, 'Doručak2', 'Doručak', 'PON;SRE;PET;NED', 'ut sem viverra aliquet eget sit amet tellus cras adipiscing', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. In eu mi bibendum neque. Facilisi morbi tempus iaculis urna id volutpat lacus laoreet non. Turpis massa tincidunt dui ut. A diam sollicitudin tempor id. Volutpat commodo sed egestas egestas fringilla phasellus faucibus. Felis eget nunc lobortis mattis aliquam. Rhoncus dolor purus non enim praesent elementum. Egestas dui id ornare arcu odio ut sem nulla. Sed viverra ipsum nunc aliquet bibendum enim facilisis gravida.');

INSERT INTO OBROK
VALUES(13, 'Prepodnevna užina1', 'Prepodnevna užina', 'UTO;ČET;SUB', 'ut sem viverra aliquet eget sit amet tellus cras adipiscing', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. In eu mi bibendum neque. Facilisi morbi tempus iaculis urna id volutpat lacus laoreet non. Turpis massa tincidunt dui ut. A diam sollicitudin tempor id. Volutpat commodo sed egestas egestas fringilla phasellus faucibus. Felis eget nunc lobortis mattis aliquam. Rhoncus dolor purus non enim praesent elementum. Egestas dui id ornare arcu odio ut sem nulla. Sed viverra ipsum nunc aliquet bibendum enim facilisis gravida.');

INSERT INTO OBROK
VALUES(14, 'Prepodnevna užina2', 'Prepodnevna užina', 'PON;SRE;PET;NED', 'ut sem viverra aliquet eget sit amet tellus cras adipiscing', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. In eu mi bibendum neque. Facilisi morbi tempus iaculis urna id volutpat lacus laoreet non. Turpis massa tincidunt dui ut. A diam sollicitudin tempor id. Volutpat commodo sed egestas egestas fringilla phasellus faucibus. Felis eget nunc lobortis mattis aliquam. Rhoncus dolor purus non enim praesent elementum. Egestas dui id ornare arcu odio ut sem nulla. Sed viverra ipsum nunc aliquet bibendum enim facilisis gravida.');

INSERT INTO OBROK
VALUES(15, 'Ručak1', 'Ručak', 'UTO;ČET;SUB', 'ut sem viverra aliquet eget sit amet tellus cras adipiscing', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. In eu mi bibendum neque. Facilisi morbi tempus iaculis urna id volutpat lacus laoreet non. Turpis massa tincidunt dui ut. A diam sollicitudin tempor id. Volutpat commodo sed egestas egestas fringilla phasellus faucibus. Felis eget nunc lobortis mattis aliquam. Rhoncus dolor purus non enim praesent elementum. Egestas dui id ornare arcu odio ut sem nulla. Sed viverra ipsum nunc aliquet bibendum enim facilisis gravida.');

INSERT INTO OBROK
VALUES(16, 'Ručak2', 'Ručak', 'PON;SRE;PET;NED', 'ut sem viverra aliquet eget sit amet tellus cras adipiscing', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. In eu mi bibendum neque. Facilisi morbi tempus iaculis urna id volutpat lacus laoreet non. Turpis massa tincidunt dui ut. A diam sollicitudin tempor id. Volutpat commodo sed egestas egestas fringilla phasellus faucibus. Felis eget nunc lobortis mattis aliquam. Rhoncus dolor purus non enim praesent elementum. Egestas dui id ornare arcu odio ut sem nulla. Sed viverra ipsum nunc aliquet bibendum enim facilisis gravida.');

INSERT INTO OBROK
VALUES(17, 'Popodnevna užina1', 'Popodnevna užina', 'UTO;ČET;SUB', 'ut sem viverra aliquet eget sit amet tellus cras adipiscing', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. In eu mi bibendum neque. Facilisi morbi tempus iaculis urna id volutpat lacus laoreet non. Turpis massa tincidunt dui ut. A diam sollicitudin tempor id. Volutpat commodo sed egestas egestas fringilla phasellus faucibus. Felis eget nunc lobortis mattis aliquam. Rhoncus dolor purus non enim praesent elementum. Egestas dui id ornare arcu odio ut sem nulla. Sed viverra ipsum nunc aliquet bibendum enim facilisis gravida.');

INSERT INTO OBROK
VALUES(18, 'Popodnevna užina2', 'Popodnevna užina', 'PON;SRE;PET;NED', 'ut sem viverra aliquet eget sit amet tellus cras adipiscing', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. In eu mi bibendum neque. Facilisi morbi tempus iaculis urna id volutpat lacus laoreet non. Turpis massa tincidunt dui ut. A diam sollicitudin tempor id. Volutpat commodo sed egestas egestas fringilla phasellus faucibus. Felis eget nunc lobortis mattis aliquam. Rhoncus dolor purus non enim praesent elementum. Egestas dui id ornare arcu odio ut sem nulla. Sed viverra ipsum nunc aliquet bibendum enim facilisis gravida.');

INSERT INTO OBROK
VALUES(19, 'Večera1', 'Večera', 'UTO;ČET;SUB', 'ut sem viverra aliquet eget sit amet tellus cras adipiscing', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. In eu mi bibendum neque. Facilisi morbi tempus iaculis urna id volutpat lacus laoreet non. Turpis massa tincidunt dui ut. A diam sollicitudin tempor id. Volutpat commodo sed egestas egestas fringilla phasellus faucibus. Felis eget nunc lobortis mattis aliquam. Rhoncus dolor purus non enim praesent elementum. Egestas dui id ornare arcu odio ut sem nulla. Sed viverra ipsum nunc aliquet bibendum enim facilisis gravida.');

INSERT INTO OBROK
VALUES(20, 'Večera2', 'Večera', 'PON;SRE;PET;NED', 'ut sem viverra aliquet eget sit amet tellus cras adipiscing', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. In eu mi bibendum neque. Facilisi morbi tempus iaculis urna id volutpat lacus laoreet non. Turpis massa tincidunt dui ut. A diam sollicitudin tempor id. Volutpat commodo sed egestas egestas fringilla phasellus faucibus. Felis eget nunc lobortis mattis aliquam. Rhoncus dolor purus non enim praesent elementum. Egestas dui id ornare arcu odio ut sem nulla. Sed viverra ipsum nunc aliquet bibendum enim facilisis gravida.');

#PLAN3
INSERT INTO OBROK
VALUES(21, 'Doručak1', 'Doručak', 'UTO;ČET;SUB', 'ut sem viverra aliquet eget sit amet tellus cras adipiscing', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. In eu mi bibendum neque. Facilisi morbi tempus iaculis urna id volutpat lacus laoreet non. Turpis massa tincidunt dui ut. A diam sollicitudin tempor id. Volutpat commodo sed egestas egestas fringilla phasellus faucibus. Felis eget nunc lobortis mattis aliquam. Rhoncus dolor purus non enim praesent elementum. Egestas dui id ornare arcu odio ut sem nulla. Sed viverra ipsum nunc aliquet bibendum enim facilisis gravida.');

INSERT INTO OBROK
VALUES(22, 'Doručak2', 'Doručak', 'PON;SRE;PET;NED', 'ut sem viverra aliquet eget sit amet tellus cras adipiscing', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. In eu mi bibendum neque. Facilisi morbi tempus iaculis urna id volutpat lacus laoreet non. Turpis massa tincidunt dui ut. A diam sollicitudin tempor id. Volutpat commodo sed egestas egestas fringilla phasellus faucibus. Felis eget nunc lobortis mattis aliquam. Rhoncus dolor purus non enim praesent elementum. Egestas dui id ornare arcu odio ut sem nulla. Sed viverra ipsum nunc aliquet bibendum enim facilisis gravida.');

INSERT INTO OBROK
VALUES(23, 'Prepodnevna užina1', 'Prepodnevna užina', 'UTO;ČET;SUB', 'ut sem viverra aliquet eget sit amet tellus cras adipiscing', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. In eu mi bibendum neque. Facilisi morbi tempus iaculis urna id volutpat lacus laoreet non. Turpis massa tincidunt dui ut. A diam sollicitudin tempor id. Volutpat commodo sed egestas egestas fringilla phasellus faucibus. Felis eget nunc lobortis mattis aliquam. Rhoncus dolor purus non enim praesent elementum. Egestas dui id ornare arcu odio ut sem nulla. Sed viverra ipsum nunc aliquet bibendum enim facilisis gravida.');

INSERT INTO OBROK
VALUES(24, 'Prepodnevna užina2', 'Prepodnevna užina', 'PON;SRE;PET;NED', 'ut sem viverra aliquet eget sit amet tellus cras adipiscing', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. In eu mi bibendum neque. Facilisi morbi tempus iaculis urna id volutpat lacus laoreet non. Turpis massa tincidunt dui ut. A diam sollicitudin tempor id. Volutpat commodo sed egestas egestas fringilla phasellus faucibus. Felis eget nunc lobortis mattis aliquam. Rhoncus dolor purus non enim praesent elementum. Egestas dui id ornare arcu odio ut sem nulla. Sed viverra ipsum nunc aliquet bibendum enim facilisis gravida.');

INSERT INTO OBROK
VALUES(25, 'Popodnevna užina1', 'Popodnevna užina', 'UTO;ČET;SUB', 'ut sem viverra aliquet eget sit amet tellus cras adipiscing', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. In eu mi bibendum neque. Facilisi morbi tempus iaculis urna id volutpat lacus laoreet non. Turpis massa tincidunt dui ut. A diam sollicitudin tempor id. Volutpat commodo sed egestas egestas fringilla phasellus faucibus. Felis eget nunc lobortis mattis aliquam. Rhoncus dolor purus non enim praesent elementum. Egestas dui id ornare arcu odio ut sem nulla. Sed viverra ipsum nunc aliquet bibendum enim facilisis gravida.');

INSERT INTO OBROK
VALUES(26, 'Popodnevna užina2', 'Popodnevna užina', 'PON;SRE;PET;NED', 'ut sem viverra aliquet eget sit amet tellus cras adipiscing', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. In eu mi bibendum neque. Facilisi morbi tempus iaculis urna id volutpat lacus laoreet non. Turpis massa tincidunt dui ut. A diam sollicitudin tempor id. Volutpat commodo sed egestas egestas fringilla phasellus faucibus. Felis eget nunc lobortis mattis aliquam. Rhoncus dolor purus non enim praesent elementum. Egestas dui id ornare arcu odio ut sem nulla. Sed viverra ipsum nunc aliquet bibendum enim facilisis gravida.');

#PLAN4
INSERT INTO OBROK
VALUES(27, 'Doručak1', 'Doručak', 'UTO;ČET;SUB', 'ut sem viverra aliquet eget sit amet tellus cras adipiscing', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. In eu mi bibendum neque. Facilisi morbi tempus iaculis urna id volutpat lacus laoreet non. Turpis massa tincidunt dui ut. A diam sollicitudin tempor id. Volutpat commodo sed egestas egestas fringilla phasellus faucibus. Felis eget nunc lobortis mattis aliquam. Rhoncus dolor purus non enim praesent elementum. Egestas dui id ornare arcu odio ut sem nulla. Sed viverra ipsum nunc aliquet bibendum enim facilisis gravida.');

INSERT INTO OBROK
VALUES(28, 'Doručak2', 'Doručak', 'PON;SRE;PET;NED', 'ut sem viverra aliquet eget sit amet tellus cras adipiscing', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. In eu mi bibendum neque. Facilisi morbi tempus iaculis urna id volutpat lacus laoreet non. Turpis massa tincidunt dui ut. A diam sollicitudin tempor id. Volutpat commodo sed egestas egestas fringilla phasellus faucibus. Felis eget nunc lobortis mattis aliquam. Rhoncus dolor purus non enim praesent elementum. Egestas dui id ornare arcu odio ut sem nulla. Sed viverra ipsum nunc aliquet bibendum enim facilisis gravida.');

INSERT INTO OBROK
VALUES(29, 'Ručak1', 'Ručak', 'UTO;ČET;SUB', 'ut sem viverra aliquet eget sit amet tellus cras adipiscing', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. In eu mi bibendum neque. Facilisi morbi tempus iaculis urna id volutpat lacus laoreet non. Turpis massa tincidunt dui ut. A diam sollicitudin tempor id. Volutpat commodo sed egestas egestas fringilla phasellus faucibus. Felis eget nunc lobortis mattis aliquam. Rhoncus dolor purus non enim praesent elementum. Egestas dui id ornare arcu odio ut sem nulla. Sed viverra ipsum nunc aliquet bibendum enim facilisis gravida.');

INSERT INTO OBROK
VALUES(30, 'Ručak2', 'Ručak', 'PON;SRE;PET;NED', 'ut sem viverra aliquet eget sit amet tellus cras adipiscing', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. In eu mi bibendum neque. Facilisi morbi tempus iaculis urna id volutpat lacus laoreet non. Turpis massa tincidunt dui ut. A diam sollicitudin tempor id. Volutpat commodo sed egestas egestas fringilla phasellus faucibus. Felis eget nunc lobortis mattis aliquam. Rhoncus dolor purus non enim praesent elementum. Egestas dui id ornare arcu odio ut sem nulla. Sed viverra ipsum nunc aliquet bibendum enim facilisis gravida.');

INSERT INTO OBROK
VALUES(31, 'Večera1', 'Večera', 'UTO;ČET;SUB', 'ut sem viverra aliquet eget sit amet tellus cras adipiscing', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. In eu mi bibendum neque. Facilisi morbi tempus iaculis urna id volutpat lacus laoreet non. Turpis massa tincidunt dui ut. A diam sollicitudin tempor id. Volutpat commodo sed egestas egestas fringilla phasellus faucibus. Felis eget nunc lobortis mattis aliquam. Rhoncus dolor purus non enim praesent elementum. Egestas dui id ornare arcu odio ut sem nulla. Sed viverra ipsum nunc aliquet bibendum enim facilisis gravida.');

INSERT INTO OBROK
VALUES(32, 'Večera2', 'Večera', 'PON;SRE;PET;NED', 'ut sem viverra aliquet eget sit amet tellus cras adipiscing', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. In eu mi bibendum neque. Facilisi morbi tempus iaculis urna id volutpat lacus laoreet non. Turpis massa tincidunt dui ut. A diam sollicitudin tempor id. Volutpat commodo sed egestas egestas fringilla phasellus faucibus. Felis eget nunc lobortis mattis aliquam. Rhoncus dolor purus non enim praesent elementum. Egestas dui id ornare arcu odio ut sem nulla. Sed viverra ipsum nunc aliquet bibendum enim facilisis gravida.');

#PLAN5
INSERT INTO OBROK
VALUES(33, 'Doručak1', 'Doručak', 'UTO;ČET;SUB', 'ut sem viverra aliquet eget sit amet tellus cras adipiscing', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. In eu mi bibendum neque. Facilisi morbi tempus iaculis urna id volutpat lacus laoreet non. Turpis massa tincidunt dui ut. A diam sollicitudin tempor id. Volutpat commodo sed egestas egestas fringilla phasellus faucibus. Felis eget nunc lobortis mattis aliquam. Rhoncus dolor purus non enim praesent elementum. Egestas dui id ornare arcu odio ut sem nulla. Sed viverra ipsum nunc aliquet bibendum enim facilisis gravida.');

INSERT INTO OBROK
VALUES(34, 'Doručak2', 'Doručak', 'PON;SRE;PET;NED', 'ut sem viverra aliquet eget sit amet tellus cras adipiscing', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. In eu mi bibendum neque. Facilisi morbi tempus iaculis urna id volutpat lacus laoreet non. Turpis massa tincidunt dui ut. A diam sollicitudin tempor id. Volutpat commodo sed egestas egestas fringilla phasellus faucibus. Felis eget nunc lobortis mattis aliquam. Rhoncus dolor purus non enim praesent elementum. Egestas dui id ornare arcu odio ut sem nulla. Sed viverra ipsum nunc aliquet bibendum enim facilisis gravida.');

INSERT INTO OBROK
VALUES(35, 'Ručak1', 'Ručak', 'UTO;ČET;SUB', 'ut sem viverra aliquet eget sit amet tellus cras adipiscing', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. In eu mi bibendum neque. Facilisi morbi tempus iaculis urna id volutpat lacus laoreet non. Turpis massa tincidunt dui ut. A diam sollicitudin tempor id. Volutpat commodo sed egestas egestas fringilla phasellus faucibus. Felis eget nunc lobortis mattis aliquam. Rhoncus dolor purus non enim praesent elementum. Egestas dui id ornare arcu odio ut sem nulla. Sed viverra ipsum nunc aliquet bibendum enim facilisis gravida.');

INSERT INTO OBROK
VALUES(36, 'Ručak2', 'Ručak', 'PON;SRE;PET;NED', 'ut sem viverra aliquet eget sit amet tellus cras adipiscing', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. In eu mi bibendum neque. Facilisi morbi tempus iaculis urna id volutpat lacus laoreet non. Turpis massa tincidunt dui ut. A diam sollicitudin tempor id. Volutpat commodo sed egestas egestas fringilla phasellus faucibus. Felis eget nunc lobortis mattis aliquam. Rhoncus dolor purus non enim praesent elementum. Egestas dui id ornare arcu odio ut sem nulla. Sed viverra ipsum nunc aliquet bibendum enim facilisis gravida.');

INSERT INTO OBROK
VALUES(37, 'Večera1', 'Večera', 'UTO;ČET;SUB', 'ut sem viverra aliquet eget sit amet tellus cras adipiscing', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. In eu mi bibendum neque. Facilisi morbi tempus iaculis urna id volutpat lacus laoreet non. Turpis massa tincidunt dui ut. A diam sollicitudin tempor id. Volutpat commodo sed egestas egestas fringilla phasellus faucibus. Felis eget nunc lobortis mattis aliquam. Rhoncus dolor purus non enim praesent elementum. Egestas dui id ornare arcu odio ut sem nulla. Sed viverra ipsum nunc aliquet bibendum enim facilisis gravida.');

INSERT INTO OBROK
VALUES(38, 'Večera2', 'Večera', 'PON;SRE;PET;NED', 'ut sem viverra aliquet eget sit amet tellus cras adipiscing', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. In eu mi bibendum neque. Facilisi morbi tempus iaculis urna id volutpat lacus laoreet non. Turpis massa tincidunt dui ut. A diam sollicitudin tempor id. Volutpat commodo sed egestas egestas fringilla phasellus faucibus. Felis eget nunc lobortis mattis aliquam. Rhoncus dolor purus non enim praesent elementum. Egestas dui id ornare arcu odio ut sem nulla. Sed viverra ipsum nunc aliquet bibendum enim facilisis gravida.');
