#Petrija:
#plan1:
INSERT INTO PLAN_ISHRANE_OBROK
VALUES(1, 1, 1);

INSERT INTO PLAN_ISHRANE_OBROK
VALUES(2, 1, 2);

INSERT INTO PLAN_ISHRANE_OBROK
VALUES(3, 1, 3);

INSERT INTO PLAN_ISHRANE_OBROK
VALUES(4, 1, 4);

INSERT INTO PLAN_ISHRANE_OBROK
VALUES(5, 1, 5);

INSERT INTO PLAN_ISHRANE_OBROK
VALUES(6, 1, 6);

INSERT INTO PLAN_ISHRANE_OBROK
VALUES(7, 1, 7);

INSERT INTO PLAN_ISHRANE_OBROK
VALUES(8, 1, 8);

INSERT INTO PLAN_ISHRANE_OBROK
VALUES(9, 1, 9);

INSERT INTO PLAN_ISHRANE_OBROK
VALUES(10, 1, 10);

#plan2:
INSERT INTO PLAN_ISHRANE_OBROK
VALUES(11, 2, 11);

INSERT INTO PLAN_ISHRANE_OBROK
VALUES(12, 2, 12);

INSERT INTO PLAN_ISHRANE_OBROK
VALUES(13, 2, 13);

INSERT INTO PLAN_ISHRANE_OBROK
VALUES(14, 2, 14);

INSERT INTO PLAN_ISHRANE_OBROK
VALUES(15, 2, 15);

INSERT INTO PLAN_ISHRANE_OBROK
VALUES(16, 2, 16);

INSERT INTO PLAN_ISHRANE_OBROK
VALUES(17, 2, 17);

INSERT INTO PLAN_ISHRANE_OBROK
VALUES(18, 2, 18);

INSERT INTO PLAN_ISHRANE_OBROK
VALUES(19, 2, 19);

INSERT INTO PLAN_ISHRANE_OBROK
VALUES(20, 2, 20);

#Luna:
#plan1:
INSERT INTO PLAN_ISHRANE_OBROK
VALUES(21, 3, 21);

INSERT INTO PLAN_ISHRANE_OBROK
VALUES(22, 3, 22);

INSERT INTO PLAN_ISHRANE_OBROK
VALUES(23, 3, 23);

INSERT INTO PLAN_ISHRANE_OBROK
VALUES(24, 3, 24);

INSERT INTO PLAN_ISHRANE_OBROK
VALUES(25, 3, 25);

INSERT INTO PLAN_ISHRANE_OBROK
VALUES(26, 3, 26);

#Todor:
#plan1:
INSERT INTO PLAN_ISHRANE_OBROK
VALUES(27, 4, 27);

INSERT INTO PLAN_ISHRANE_OBROK
VALUES(28, 4, 28);

INSERT INTO PLAN_ISHRANE_OBROK
VALUES(29, 4, 29);

INSERT INTO PLAN_ISHRANE_OBROK
VALUES(30, 4, 30);

INSERT INTO PLAN_ISHRANE_OBROK
VALUES(31, 4, 31);

INSERT INTO PLAN_ISHRANE_OBROK
VALUES(32, 4, 32);

#plan2:
INSERT INTO PLAN_ISHRANE_OBROK
VALUES(33, 5, 33);

INSERT INTO PLAN_ISHRANE_OBROK
VALUES(34, 5, 34);

INSERT INTO PLAN_ISHRANE_OBROK
VALUES(35, 5, 35);

INSERT INTO PLAN_ISHRANE_OBROK
VALUES(36, 5, 36);

INSERT INTO PLAN_ISHRANE_OBROK
VALUES(37, 5, 37);

INSERT INTO PLAN_ISHRANE_OBROK
VALUES(38, 5, 38);